### ISSUE TITLE
重启错误 华为 大佬给看下？

### ISSUE THREAD

**Issue by Wanghuizhijia** [SeanChengN/JAViewer#11]
Build version: 2.0.0-fuck-0331 
Current date: 2020-04-22 11:14:08 
Device: HUAWEI HMA-AL00 
 
Stack trace:  
java.lang.RuntimeException: Unable to start activity ComponentInfo{io.github.javiewer/io.github.javiewer.activity.MainActivity}: java.lang.IllegalArgumentException: baseUrl must end in /: https://avmask.com/cn
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3760)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3939)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:91)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:149)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:103)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2373)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:213)
	at android.app.ActivityThread.main(ActivityThread.java:8147)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1101)
Caused by: java.lang.IllegalArgumentException: baseUrl must end in /: https://avmask.com/cn
	at retrofit2.Retrofit$Builder.baseUrl(Retrofit.java:527)
	at retrofit2.Retrofit$Builder.baseUrl(Retrofit.java:470)
	at io.github.javiewer.JAViewer.recreateService(JAViewer.java:104)
	at io.github.javiewer.activity.MainActivity.onCreate(MainActivity.java:108)
	at android.app.Activity.performCreate(Activity.java:8066)
	at android.app.Activity.performCreate(Activity.java:8054)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1313)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3733)
	... 11 more

**Comment by SeanChengN** [comment]
如果是打开收藏奔溃，查看Q5，否则查看Q3。
